services:
  web:
    env_file:
      - "docker/env/web"
      - "docker/env/web.local"
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: .
      dockerfile: "Dockerfile"
      args:
        DEV_BUILD: "true"
    pull_policy: build
    image: brasil-io-web:latest
    command: bash -c "/app/bin/release.sh && /app/bin/web.sh"
    volumes:
      - ${PWD}/docker/data/web:/data
      - ${PWD}:/app
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
      messaging:
        condition: service_started

  worker:
    env_file:
      - "docker/env/web"
      - "docker/env/web.local"
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: .
      dockerfile: "Dockerfile"
      args:
        DEV_BUILD: "true"
    pull_policy: build
    image: brasil-io-web:latest
    command: /app/bin/worker.sh
    volumes:
      - ${PWD}/docker/data/web:/data
      - ${PWD}:/app
    depends_on:
      db:
        condition: service_healthy
      messaging:
        condition: service_started

  db:
    env_file:
      - "docker/env/db"
      - "docker/env/db.local"
    user: "${UID:-1000}:${GID:-1000}"
    shm_size: "8g"
    image: "postgres:16.3-bookworm"
    command: -c "config_file=/etc/postgresql/postgresql.conf"
    volumes:
      - ${PWD}/docker/data/db:/var/lib/postgresql/data
      - ${PWD}/docker/conf/db/postgresql.dev.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      retries: 5

  mail:
    image: "mailhog/mailhog:latest"
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - "docker/env/mail"
      - "docker/env/mail.local"
    volumes:
      - ${PWD}/docker/data/mail:/data
    ports:
      - "8025:8025"

  messaging:
    image: "redis:6.2-alpine"
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - "docker/env/messaging"
      - "docker/env/messaging.local"
    volumes:
      - ${PWD}/docker/data/messaging:/data

  storage:
    image: "minio/minio:latest"
    env_file:
      - "docker/env/storage"
      - "docker/env/storage.local"
    volumes:
      - ${PWD}/docker/data/storage:/data
    ports:
      - 9000:9000
      - 9001:9001
    command: ["server", "/data", "--console-address", ":9001"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/index.html || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
