x-web-common: &web-common
  env_file:
    - path: "docker/env/web"
      required: true
    - path: "docker/env/web.local"
      required: false
  user: "${UID:-1000}:${GID:-1000}"
  build:
    context: .
    dockerfile: "Dockerfile"
    args:
      ENV_TYPE: "development"
  pull_policy: build
  image: brasil-io-web:latest
  volumes:
    - ${PWD}/docker/data/web/:/data/
    - ${PWD}/:/app/
  depends_on:
    db:
      condition: service_healthy
    messaging:
      condition: service_started

services:
  web:
    <<: *web-common
    command: bash -c "/app/bin/release.sh && /app/bin/web.sh"
    ports:
      - 5000:5000

  worker:
    <<: *web-common
    deploy:
      mode: replicated
      replicas: 2
    command: /app/bin/worker.sh

  mail-worker:
    <<: *web-common
    command: /app/bin/mail-worker.sh

  db:
    env_file:
      - path: "docker/env/db"
        required: true
      - path: "docker/env/db.local"
        required: false
    shm_size: ${DB_SHM_SIZE:-8g}
    image: "postgres:17.6-trixie"
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    volumes:
      - ${PWD}/docker/data/db/:/data/:rw
      - ${PWD}/docker/conf/db/postgresql.dev.conf:/etc/postgresql/postgresql.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      retries: 5

  mail:
    env_file:
      - path: "docker/env/mail"
        required: true
      - path: "docker/env/mail.local"
        required: false
    image: "mailhog/mailhog:latest"
    volumes:
      - ${PWD}/docker/data/mail/:/data/
    ports:
      - "8025:8025"

  messaging:
    env_file:
      - path: "docker/env/messaging"
        required: true
      - path: "docker/env/messaging.local"
        required: false
    image: "redis:6.2-alpine"
    volumes:
      - ${PWD}/docker/data/messaging/:/data/

  storage:
    env_file:
      - path: "docker/env/storage"
        required: true
      - path: "docker/env/storage.local"
        required: false
    image: "minio/minio:latest"
    volumes:
      - ${PWD}/docker/data/storage/:/data/
    ports:
      - 9000:9000
      - 9001:9001
    command: ["server", "/data", "--console-address", ":9001"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/index.html || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
