# coding: utf-8

unidades_federativas = [
        {'codigo-ibge': 12, 'nome': u'Acre', 'sigla': u'AC'},
        {'codigo-ibge': 27, 'nome': u'Alagoas', 'sigla': u'AL'},
        {'codigo-ibge': 16, 'nome': u'Amap\xe1', 'sigla': u'AP'},
        {'codigo-ibge': 13, 'nome': u'Amazonas', 'sigla': u'AM'},
        {'codigo-ibge': 29, 'nome': u'Bahia', 'sigla': u'BA'},
        {'codigo-ibge': 23, 'nome': u'Cear\xe1', 'sigla': u'CE'},
        {'codigo-ibge': 53, 'nome': u'Distrito Federal', 'sigla': u'DF'},
        {'codigo-ibge': 32, 'nome': u'Esp\xedrito Santo', 'sigla': u'ES'},
        {'codigo-ibge': 52, 'nome': u'Goi\xe1s', 'sigla': u'GO'},
        {'codigo-ibge': 21, 'nome': u'Maranh\xe3o', 'sigla': u'MA'},
        {'codigo-ibge': 51, 'nome': u'Mato Grosso', 'sigla': u'MT'},
        {'codigo-ibge': 50, 'nome': u'Mato Grosso do Sul', 'sigla': u'MS'},
        {'codigo-ibge': 31, 'nome': u'Minas Gerais', 'sigla': u'MG'},
        {'codigo-ibge': 41, 'nome': u'Paran\xe1', 'sigla': u'PR'},
        {'codigo-ibge': 25, 'nome': u'Para\xedba', 'sigla': u'PB'},
        {'codigo-ibge': 15, 'nome': u'Par\xe1', 'sigla': u'PA'},
        {'codigo-ibge': 26, 'nome': u'Pernambuco', 'sigla': u'PE'},
        {'codigo-ibge': 22, 'nome': u'Piau\xed', 'sigla': u'PI'},
        {'codigo-ibge': 24, 'nome': u'Rio Grande do Norte', 'sigla': u'RN'},
        {'codigo-ibge': 43, 'nome': u'Rio Grande do Sul', 'sigla': u'RS'},
        {'codigo-ibge': 33, 'nome': u'Rio de Janeiro', 'sigla': u'RJ'},
        {'codigo-ibge': 11, 'nome': u'Rond\xf4nia', 'sigla': u'RO'},
        {'codigo-ibge': 14, 'nome': u'Roraima', 'sigla': u'RR'},
        {'codigo-ibge': 42, 'nome': u'Santa Catarina', 'sigla': u'SC'},
        {'codigo-ibge': 28, 'nome': u'Sergipe', 'sigla': u'SE'},
        {'codigo-ibge': 35, 'nome': u'S\xe3o Paulo', 'sigla': u'SP'},
        {'codigo-ibge': 17, 'nome': u'Tocantins', 'sigla': u'TO'}, ]
