# Generated by Django 2.0.3 on 2018-03-26 13:41

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("author_name", models.CharField(max_length=255)),
                ("author_url", models.URLField(blank=True, max_length=2000, null=True)),
                ("code_url", models.URLField(max_length=2000)),
                ("description", models.TextField()),
                ("license_name", models.CharField(max_length=255)),
                ("license_url", models.URLField(max_length=2000)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("source_name", models.CharField(max_length=255)),
                ("source_url", models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("index", models.BooleanField()),
                ("max_length", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=63)),
                ("options", django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ("show", models.BooleanField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("binary", "binary"),
                            ("bool", "bool"),
                            ("date", "date"),
                            ("datetime", "datetime"),
                            ("decimal", "decimal"),
                            ("email", "email"),
                            ("float", "float"),
                            ("integer", "integer"),
                            ("json", "json"),
                            ("percent", "percent"),
                            ("text", "text"),
                        ],
                        max_length=15,
                    ),
                ),
                ("dataset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.Dataset")),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=2000)),
                ("dataset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.Dataset")),
            ],
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("default", models.BooleanField()),
                ("name", models.CharField(max_length=255)),
                ("options", django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                (
                    "ordering",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=63), size=None),
                ),
                ("dataset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.Dataset")),
            ],
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("collected_at", models.DateField()),
                ("download_url", models.URLField(max_length=2000)),
                ("name", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField()),
                ("dataset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.Dataset")),
            ],
        ),
        migrations.AddField(
            model_name="table",
            name="version",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.Version"),
        ),
        migrations.AddField(
            model_name="field",
            name="table",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.Table"),
        ),
        migrations.AddField(
            model_name="field",
            name="version",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.Version"
            ),
        ),
    ]
