# Generated by Django 2.0.3 on 2018-05-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20180501_2154"),
    ]

    operations = [
        migrations.AddField(model_name="field", name="frontend_filter", field=models.BooleanField(default=False),),
    ]
