# Generated by Django 2.0.3 on 2018-06-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_data_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
