# Generated by Django 2.0.3 on 2018-08-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180717_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
