# Generated by Django 2.1.1 on 2018-09-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_auto_20180824_2201"),
    ]

    operations = [
        migrations.RenameField(model_name="table", old_name="last_update", new_name="import_date",),
    ]
