# Generated by Django 2.1.1 on 2018-09-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180824_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='last_update',
            new_name='import_date',
        ),
        migrations.AlterField(
            model_name='field',
            name='frontend_filter',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='field',
            name='has_choices',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='field',
            name='null',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='obfuscate',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='field',
            name='show',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='show_on_frontend',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
