# Generated by Django 3.0.5 on 2020-05-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_table_description"),
    ]

    operations = [
        migrations.AddField(model_name="table", name="hidden", field=models.BooleanField(default=False),),
    ]
