# Generated by Django 3.0.5 on 2020-07-08 19:41

from django.db import migrations


def populate_data_tables_for_existing_tables(apps, schema_editor):
    DataTable = apps.get_model("core", "DataTable")
    Table = apps.get_model("core", "Table")

    data_tables = []
    for table in Table.objects.all():
        db_table_name = "data_{}_{}".format(table.dataset.slug.replace("-", ""), table.name.replace("_", ""),)
        data_tables.append(DataTable(table=table, db_table_name=db_table_name, active=True))

    DataTable.objects.bulk_create(data_tables)


def delete_data_tables(apps, schema_editor):
    DataTable = apps.get_model("core", "DataTable")
    DataTable.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_datatable"),
    ]

    operations = [migrations.RunPython(populate_data_tables_for_existing_tables, delete_data_tables)]
