# Generated by Django 3.0.5 on 2020-08-13 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_auto_20200708_1641"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableFile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_url", models.URLField()),
                ("sha512sum", models.CharField(max_length=128)),
                ("filename", models.TextField()),
                ("size", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="table_file", to="core.Table"
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
    ]
