# Generated by Django 3.1.1 on 2020-10-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_auto_20200918_1805"),
    ]

    operations = [
        migrations.RenameField(model_name="table", old_name="filtering", new_name="filtering_fields",),
    ]
