# Generated by Django 3.1.1 on 2020-10-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_auto_20201006_1439"),
    ]

    operations = [
        migrations.AddField(
            model_name="field", name="searchable", field=models.BooleanField(blank=True, default=False),
        ),
    ]
