# Generated by Django 3.1.1 on 2020-10-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_auto_20201007_1702"),
    ]

    operations = [
        migrations.RenameField(model_name="table", old_name="search", new_name="search_fields",),
    ]
