# Generated by Django 3.1.1 on 2020-10-07 20:07

from django.db import migrations


def update_searchable_fields_flags(apps, schema_editor):
    Table = apps.get_model("core", "Table")

    for table in Table.objects.exclude(search_fields__isnull=True):
        table.field_set.filter(name__in=table.search_fields).update(searchable=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_auto_20201007_1704"),
    ]

    operations = [migrations.RunPython(update_searchable_fields_flags)]
