# Generated by Django 3.1.1 on 2020-10-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_auto_20201007_1707"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataUrlRedirect",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dataset_prev", models.SlugField(default="")),
                ("dataset_dest", models.SlugField(default="")),
                ("tablename_prev", models.SlugField(default="")),
                ("tablename_dest", models.SlugField(default="")),
                ("field_prev", models.SlugField(default="")),
                ("field_dest", models.SlugField(default="")),
            ],
        ),
    ]
