# Generated by Django 4.2.25 on 2025-11-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_auto_20201206_2132"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablefile",
            name="size",
            field=models.PositiveBigIntegerField(),
        ),
    ]
