# Generated by Django 3.1.8 on 2021-09-15 19:02

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20201206_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='short_description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
