# Generated by Django 3.1.8 on 2021-09-15 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_table_short_description"),
    ]

    operations = [
        migrations.RenameField(model_name="dataset", old_name="description", new_name="short_description",),
    ]
