# Generated by Django 3.1.8 on 2021-09-15 20:31

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_dataset_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='short_description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
