# Generated by Django 4.2.30 on 2026-05-30 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("brasilio_auth", "0002_activationresend"),
    ]

    operations = [
        migrations.CreateModel(
            name="NormalizedEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.EmailField(
                        help_text="Forma canônica do e-mail (sem plus-addressing, sem pontos no Gmail, googlemail unificado).",
                        max_length=254,
                        unique=True,
                        verbose_name="E-mail normalizado",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalized_email",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "E-mail normalizado",
                "verbose_name_plural": "E-mails normalizados",
                "ordering": ("value",),
            },
        ),
    ]
