# Generated by Django 4.2.30 on 2026-05-30 03:50

from django.conf import settings
from django.db import migrations

from brasilio_auth.validators import normalize_email_address


def popular_normalized_email(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    NormalizedEmail = apps.get_model("brasilio_auth", "NormalizedEmail")

    vistos = set()
    objs = []
    # Ativas primeiro, desempate pelo cadastro mais antigo: o dono do normalizado deve ser quem pode logar por alias.
    for user in User.objects.order_by("-is_active", "id").iterator():
        if not user.email:
            continue
        normalizado = normalize_email_address(user.email)
        if normalizado in vistos:  # Outro usuário (ativo ou mais antigo) já possui esse mesmo email normalizado
            continue
        vistos.add(normalizado)
        objs.append(NormalizedEmail(user_id=user.id, value=normalizado))
    NormalizedEmail.objects.bulk_create(objs)


def remover_normalized_email(apps, schema_editor):
    NormalizedEmail = apps.get_model("brasilio_auth", "NormalizedEmail")
    NormalizedEmail.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("brasilio_auth", "0003_normalizedemail"),
    ]
    operations = [migrations.RunPython(popular_normalized_email, remover_normalized_email)]
