# Generated by Django 4.2.15 on 2024-08-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidacy",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("person_uuid", models.UUIDField(db_index=True)),
                ("ano", models.SmallIntegerField(blank=True, null=True)),
                ("cargo", models.TextField(blank=True, max_length=31, null=True)),
                ("nome", models.TextField(blank=True, null=True)),
                ("nome_urna", models.TextField(blank=True, max_length=31, null=True)),
                ("genero", models.TextField(blank=True, null=True)),
                ("data_nascimento", models.TextField(blank=True, null=True)),
                (
                    "numero_sequencial",
                    models.TextField(blank=True, max_length=15, null=True),
                ),
                (
                    "sigla_partido",
                    models.TextField(blank=True, max_length=15, null=True),
                ),
                (
                    "sigla_unidade_federativa",
                    models.TextField(blank=True, max_length=2, null=True),
                ),
                ("composicao_legenda", models.TextField(blank=True, null=True)),
                (
                    "totalizacao_turno",
                    models.TextField(blank=True, max_length=16, null=True),
                ),
                (
                    "unidade_eleitoral",
                    models.TextField(blank=True, max_length=32, null=True),
                ),
                ("situacao", models.TextField(blank=True, max_length=15, null=True)),
            ],
            options={
                "verbose_name": "Candidatura",
                "verbose_name_plural": "Candidaturas",
                "ordering": ["-ano"],
                "indexes": [
                    models.Index(fields=["ano"], name="elections_c_ano_40a163_idx")
                ],
            },
        ),
    ]
