# Generated by Django 4.2.15 on 2024-08-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidacy",
            name="cargo_slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidacy",
            name="nome_urna_slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
