# Generated by Django 4.2.15 on 2024-08-29 12:11

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0002_candidacy_cargo_slug_candidacy_nome_urna_slug"),
    ]

    operations = [UnaccentExtension()]
