# Generated by Django 4.2.15 on 2024-09-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0003_unaccent"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidacy",
            name="municipio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
