# Generated by Django 4.2.15 on 2024-09-03 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0004_candidacy_municipio"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidacyMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
