# Generated by Django 4.2.16 on 2024-09-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0005_candidacymetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidacy",
            name="municipio_slug",
            field=models.TextField(blank=True, null=True),
        ),
    ]
