# Generated by Django 4.2.16 on 2024-09-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0006_candidacy_municipio_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidacy",
            name="estado_civil",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidacy",
            name="etnia",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidacy",
            name="grau_instrucao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidacy",
            name="ocupacao",
            field=models.TextField(blank=True, null=True),
        ),
    ]
