# Generated by Django 4.2.16 on 2024-09-18 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0007_candidacy_estado_civil_candidacy_etnia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialNetworkMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("icon", models.CharField(max_length=255)),
                ("url_prefix", models.URLField(max_length=255)),
            ],
            options={
                "verbose_name": "Social network metadata",
                "verbose_name_plural": "Social networks metadata",
            },
        ),
        migrations.CreateModel(
            name="CandidacySocialNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "candidacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_networks",
                        to="elections.candidacy",
                    ),
                ),
                (
                    "social_network_metadata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="elections.socialnetworkmetadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidacy social network",
                "verbose_name_plural": "Candidacy social networks",
            },
        ),
    ]
