# Generated by Django 4.2.16 on 2024-09-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0007_candidacy_estado_civil_candidacy_etnia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidacy",
            name="numero_urna",
            field=models.TextField(blank=True, null=True),
        ),
    ]
