# Generated by Django 4.2.16 on 2024-09-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0008_candidacy_numero_urna"),
        ("elections", "0008_socialnetworkmetadata_candidacysocialnetwork"),
    ]

    operations = []
