# Generated by Django 4.2.16 on 2024-09-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0009_merge_20240923_0939"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidacy",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
