# Generated by Django 4.2.16 on 2024-09-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0010_alter_candidacy_data_nascimento"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidacysocialnetwork",
            options={
                "ordering": ("position",),
                "verbose_name": "Candidacy social network",
                "verbose_name_plural": "Candidacy social networks",
            },
        ),
        migrations.AddField(
            model_name="candidacysocialnetwork",
            name="position",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
