"""
Django settings for the project.

Generated by 'django-admin startproject' using Django 4.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
import sentry_sdk
from decouple import Csv, config
from django.utils.log import DEFAULT_LOGGING
from sentry_sdk.integrations.django import DjangoIntegration

from django.urls import reverse_lazy
from sentry_sdk.integrations.rq import RqIntegration


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool, default=False)

# Hostname
ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv())
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", cast=Csv())
APP_HOST = config("APP_HOST", default="brasil.io")
BLOCKED_AGENTS = config("BLOCKED_AGENTS", cast=Csv(), default="")
BLOCKED_WEB_AGENTS = [a.lower() for a in config("BLOCKED_WEB_AGENTS", cast=Csv(), default="")]
SESSION_COOKIE_DOMAIN = config("SESSION_COOKIE_DOMAIN", default=None)  # ".brasil.io"  # wildcard brasil.io subdomains
BRASILIO_API_HOST = config("BRASILIO_API_HOST", default="api.brasil.io")

PRODUCTION = config("PRODUCTION", cast=bool, default=True)
SECRET_KEY = config("SECRET_KEY")
FERNET_KEY = config("FERNET_KEY")

# Application definition

INSTALLED_APPS = [
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.humanize",
    "django.contrib.messages",
    "django.contrib.postgres",
    "django.contrib.sessions",
    "django.contrib.staticfiles",
    # Third-party apps
    "cachalot",
    "corsheaders",
    "django_extensions",
    "django_recaptcha",
    "django_registration",
    "django_rq",
    "markdownx",
    "rangefilter",
    "rest_framework",
    "sorl.thumbnail",
    "storages",
    # Project apps
    "api",
    "core",
    "brasilio_auth",
    "covid19.apps.Covid19Config",
    "dashboard",
    "traffic_control",
]

MIDDLEWARE = [
    "project.middlewares.host_based_url_conf",
    "django.middleware.security.SecurityMiddleware",
    "traffic_control.middlewares.block_suspicious_requests",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.cache.UpdateCacheMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "core.middlewares.NotLoggedUserFetchFromCacheMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
 ]
if DEBUG and config("DEBUG_SQL", cast=bool, default=False):
    MIDDLEWARE.append("utils.sqlprint.SqlPrintingMiddleware")  # TODO: may use https://pypi.org/project/sqlformatter/

ADMINS = config("ADMINS", cast=Csv(), default="")
if ADMINS:
    ADMINS = [tuple([item.strip() for item in name_email.split("|")]) for name_email in ADMINS]

ROOT_URLCONF = "project.urls"
API_ROOT_URLCONF = "project.api_urls"
APPEND_SLASH = True

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "covid19.context_processors.is_covid19_contributor",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {"default": dj_database_url.config()}
DATABASES["default"]["CONN_MAX_AGE"] = config("DATABASE_CONN_MAX_AGE", default=3600, cast=int)  # seconds
DATABASE_STATEMENT_TIMEOUT = config("DATABASE_STATEMENT_TIMEOUT", default=25000, cast=int)  # miliseconds
REDIS_URL = config("REDIS_URL")

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.AutoField"


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
AUTHENTICATION_BACKENDS = ["brasilio_auth.auth_backend.UsernameOrEmailBackend"]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "pt-br"
TIME_ZONE = "America/Sao_Paulo"
USE_I18N = True
USE_TZ = True
USE_I18N = True
USE_L10N = True
USE_THOUSAND_SEPARATOR = True
DATE_FORMAT = "d \\d\\e F \\d\\e Y"
DATETIME_FORMAT = "d \\d\\e F \\d\\e Y \\à\\s H:i:s"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = str(BASE_DIR / "collected-static")
STATICFILES_DIRS = [str(BASE_DIR / "static")]
STATICFILES_STORAGE = config("STATICFILES_STORAGE", default="django.contrib.staticfiles.storage.StaticFilesStorage")
MEDIA_URL = "/media/"
MEDIA_ROOT = config("MEDIA_ROOT", default=str(BASE_DIR / "public" / "media"))


# Storage
DEFAULT_FILE_STORAGE = config("DEFAULT_FILE_STORAGE", default="django.core.files.storage.FileSystemStorage")
DATA_DIR = config("DATA_DIR", cast=Path)
AWS_AUTO_CREATE_BUCKET = config("AWS_AUTO_CREATE_BUCKET", cast=bool, default=True)
AWS_BUCKET_ACL = config("AWS_BUCKET_ACL")
AWS_DEFAULT_ACL = config("AWS_DEFAULT_ACL")
AWS_QUERYSTRING_AUTH = False
AWS_S3_ACCESS_KEY_ID = config("AWS_S3_ACCESS_KEY_ID")
AWS_S3_CUSTOM_DOMAIN = config("AWS_S3_CUSTOM_DOMAIN", default=None)  # This is the base URL used when creating  links to files
AWS_S3_ENDPOINT_URL = config("AWS_S3_ENDPOINT_URL")  # This is the server to connect to send files
AWS_S3_SECRET_ACCESS_KEY = config("AWS_S3_SECRET_ACCESS_KEY")
AWS_S3_URL_PROTOCOL = config("AWS_S3_URL_PROTOCOL", default="https:")
AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")
AWS_IS_GZIPPED = config("AWS_IS_GZIPPED")
GZIP_CONTENT_TYPES = config("GZIP_CONTENT_TYPES")
AWS_S3_DATASETS_BUCKET_NAME = config("AWS_S3_DATASETS_BUCKET_NAME")
AWS_S3_DATASET_DOWNLOAD_CHUNK_SIZE = config("AWS_S3_DATASET_DOWNLOAD_CHUNK_SIZE", cast=int, default=8388608)
AWS_S3_DATASET_SHA512SUMS_FILENAME = config("AWS_S3_DATASET_SHA512SUMS_FILENAME", default="SHA512SUMS")
AWS_S3_DATASET_TABLES_FILES_LIST_FILENAME = config("AWS_S3_DATASET_TABLES_FILES_LIST_FILENAME", default="_meta/list.html")


# Data-related settings
DATA_URL = config("DATA_URL")

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 100,
    "EXCEPTION_HANDLER": "traffic_control.handlers.api_exception_handler",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "api.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["api.permissions.ApiIsAuthenticated"],
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.NamespaceVersioning",
}
MAX_NUM_API_TOKEN_PER_USER = config("MAX_NUM_API_TOKEN_PER_USER", cast=int, default=10)
ENABLE_API_AUTH = config("ENABLE_API_AUTH", cast=bool, default=False)

THROTTLING_RATE = config("THROTTLING_RATE")
if THROTTLING_RATE:
    REST_FRAMEWORK.update(
        {
            "DEFAULT_THROTTLE_CLASSES": [
                "rest_framework.throttling.AnonRateThrottle",
                "rest_framework.throttling.UserRateThrottle",
            ],
            "DEFAULT_THROTTLE_RATES": {"anon": THROTTLING_RATE, "user": THROTTLING_RATE,},
        }
    )
API_DEMO_URL = config("API_DEMO_URL", default="https://gist.github.com/turicas/3e3621d61415e3453cd03a1997f7473f")
API_KEYS_BLOGPOST_URL = config("API_KEYS_BLOGPOST_URL", default="https://blog.brasil.io/")


RATELIMIT_ENABLE = config("RATELIMIT_ENABLE", cast=bool, default=False)
RATELIMIT_RATE = config(
    "RATELIMIT_RATE", default="10/m"
)  # we have to force a default value, otherwise django-ratelimit breaks our app

CORS_ORIGIN_ALLOW_ALL = True

EMAIL_BACKEND = config("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_PORT = config("EMAIL_PORT", cast=int, default=587)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool, default=True)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="contato@brasil.io")
if DEBUG:
    EMAIL_FILE_PATH = MEDIA_ROOT
else:
    SENDGRID_API_KEY = config("SENDGRID_API_KEY")


# Auth conf
LOGOUT_REDIRECT_URL = "/"
LOGIN_REDIRECT_URL = "/"
LOGIN_URL = reverse_lazy("brasilio_auth:login")

DISABLE_RECAPTCHA = config("DISABLE_RECAPTCHA", cast=bool, default=False)
RECAPTCHA_PUBLIC_KEY = config("RECAPTCHA_PUBLIC_KEY")
RECAPTCHA_PRIVATE_KEY = config("RECAPTCHA_PRIVATE_KEY")

ROWS_PER_PAGE = config("ROWS_PER_PAGE", cast=int, default=50)

CACHE_INTERVAL = 900  # 15 minutes
CACHALOT_ENABLED = config("CACHE_ENABLED", cast=bool, default=True)
CACHE_MIDDLEWARE_ALIAS = "default"
CACHE_MIDDLEWARE_SECONDS = CACHE_INTERVAL
CACHE_MIDDLEWARE_KEY_PREFIX = "non_logged_user_"
CACHALOT_CACHE = "default"
CACHES = {
    "default": {
        "BACKEND": config("CACHE_BACKEND"),
        "LOCATION": REDIS_URL,
        "OPTIONS": {"CLIENT_CLASS": config("CACHE_CLIENT_CLASS")},
        "KEY_PREFIX": config("CACHE_KEY_PREFIX"),
    }
}

# django-rq config
RQ_QUEUES = {"default": {"URL": REDIS_URL, "DEFAULT_TIMEOUT": 500,}}
RQ = {
    "DEFAULT_RESULT_TTL": 60 * 60 * 24,  # 24-hours
}
RQ_BLOCKED_REQUESTS_LIST = config("RQ_BLOCKED_REQUESTS_LIST")
if not DEBUG:
    RQ_QUEUES["default"]["WORKER_CLASS"] = "project.worker.SentryAwareWorker"


# Covid19 import settings
COVID_IMPORT_PERMISSION_PREFIX = "can_import_covid_state_"
COVID_19_ADMIN_GROUP_NAME = "Admins Covid-19"
COVID_19_STATE_TOTALS_URL = (
    "https://docs.google.com/spreadsheets/d/17mmfgPAcVCeHW3548BlFtuurAvF3jeffRVO1NW7rVgQ/export?format=csv"
)
COVID19_AUTO_IMPORT_USER = "robo_covid19"

# RockecChat
ROCKETCHAT_BASE_URL = config("ROCKETCHAT_BASE_URL")
ROCKETCHAT_USERNAME = config("ROCKETCHAT_USERNAME")
ROCKETCHAT_PASSWORD = config("ROCKETCHAT_PASSWORD")


# Sentry
SENTRY_DSN = config("SENTRY_DSN", default=None)
if SENTRY_DSN:
    sentry_sdk.init(
        SENTRY_DSN,
        integrations=[DjangoIntegration(), RqIntegration()],
        send_default_pii=True,
    )

CSV_EXPORT_MAX_ROWS = config("CSV_EXPORT_MAX_ROWS", default=10_000, cast=int)


# Cloudflare
CLOUDFLARE_AUTH_EMAIL = config("CLOUDFLARE_AUTH_EMAIL")
CLOUDFLARE_AUTH_KEY = config("CLOUDFLARE_AUTH_KEY")
CLOUDFLARE_ACCOUNT_NAME = config("CLOUDFLARE_ACCOUNT_NAME")
CLOUDFLARE_BLOCKED_IPS_RULE = config("CLOUDFLARE_BLOCKED_IPS_RULE")


# Django registration
ACCOUNT_ACTIVATION_DAYS = config("ACCOUNT_ACTIVATION_DAYS", cast=int, default=7)
REGISTRATION_SALT = config("REGISTRATION_SALT", default=SECRET_KEY)
REGISTRATION_OPEN = config("REGISTRATION_OPEN", cast=bool, default=True)


# Brasil.IO presentation
NUM_RECENT_ACTIVITES_HOMEPAGE = config("NUM_RECENT_ACTIVITES_HOMEPAGE", cast=int, default=5)
DAYS_RANGE_RECENT_ACTIVITES_HOMEPAGE = config("DAYS_RANGE_RECENT_ACTIVITES_HOMEPAGE", cast=int, default=30)


# Logging
LOGGING = DEFAULT_LOGGING.copy()
LOGGING["handlers"]["null"] = {"class": "logging.NullHandler"}
LOGGING["loggers"]["django.security.DisallowedHost"] = {"handlers": ["null"], "propagate": False}
