# Generated by Django 2.2 on 2020-04-10 22:58
from localflavor.br.br_states import STATE_CHOICES

from django.conf import settings
from django.db import migrations


def create_covid19_state_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    perm_codes = ["add_statespreadsheet", "view_statespreadsheet"]
    group_permissions = Permission.objects.filter(codename__in=perm_codes)

    for uf, name in STATE_CHOICES:
        state_perm = Permission.objects.get(codename=settings.COVID_IMPORT_PERMISSION_PREFIX + uf)

        name = f"Covid-19 Import State: {name}"
        group = Group.objects.create(name=name)

        group.permissions.add(*group_permissions)
        group.permissions.add(state_perm)


def delete_covid19_state_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__startswith="Covid-19 Import State").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("covid19", "0003_auto_20200410_1939"),
    ]

    operations = [migrations.RunPython(create_covid19_state_groups, delete_covid19_state_groups,)]
