# Generated by Django 3.0.5 on 2020-06-23 18:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("covid19", "0008_auto_20200504_1455"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyBulletin",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("updated_at", models.DateField(auto_now=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("date", models.DateField()),
                ("detailed_data", django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
