# Generated by Django 3.0.5 on 2020-07-06 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("covid19", "0009_dailybulletin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statespreadsheet",
            name="peer_review",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="covid19.StateSpreadsheet"
            ),
        ),
    ]
