# Generated by Django 3.0.5 on 2020-07-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("covid19", "0011_auto_20200706_1805"),
    ]

    operations = [
        migrations.AddField(
            model_name="statespreadsheet", name="automatically_created", field=models.BooleanField(default=False),
        ),
    ]
