# Generated by Django 3.0.5 on 2020-07-13 20:21

from django.db import migrations
from django.db.models import F


def populate_automatically_created_flag(apps, schema_editor):
    StateSpreadsheet = apps.get_model("covid19", "StateSpreadsheet")
    StateSpreadsheet.objects.filter(peer_review_id=F("id")).update(automatically_created=True)


def reset_automatically_created_flag(apps, schema_editor):
    StateSpreadsheet = apps.get_model("covid19", "StateSpreadsheet")
    StateSpreadsheet.objects.filter(automatically_created=True).update(automatically_created=False)


class Migration(migrations.Migration):

    dependencies = [
        ("covid19", "0012_statespreadsheet_automatically_created"),
    ]

    operations = [migrations.RunPython(populate_automatically_created_flag, reset_automatically_created_flag)]
