# Generated by Django 3.1.1 on 2020-11-24 15:16

import covid19.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("covid19", "0014_auto_20200713_1733"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailybulletin", name="detailed_data", field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="statespreadsheet",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="statespreadsheet",
            name="data",
            field=models.JSONField(default=covid19.models.default_data_json),
        ),
        migrations.AlterField(model_name="statespreadsheet", name="date", field=models.DateField(db_index=True),),
        migrations.AlterField(
            model_name="statespreadsheet",
            name="state",
            field=models.CharField(
                choices=[
                    ("AC", "Acre"),
                    ("AL", "Alagoas"),
                    ("AP", "Amapá"),
                    ("AM", "Amazonas"),
                    ("BA", "Bahia"),
                    ("CE", "Ceará"),
                    ("DF", "Distrito Federal"),
                    ("ES", "Espírito Santo"),
                    ("GO", "Goiás"),
                    ("MA", "Maranhão"),
                    ("MT", "Mato Grosso"),
                    ("MS", "Mato Grosso do Sul"),
                    ("MG", "Minas Gerais"),
                    ("PA", "Pará"),
                    ("PB", "Paraíba"),
                    ("PR", "Paraná"),
                    ("PE", "Pernambuco"),
                    ("PI", "Piauí"),
                    ("RJ", "Rio de Janeiro"),
                    ("RN", "Rio Grande do Norte"),
                    ("RS", "Rio Grande do Sul"),
                    ("RO", "Rondônia"),
                    ("RR", "Roraima"),
                    ("SC", "Santa Catarina"),
                    ("SP", "São Paulo"),
                    ("SE", "Sergipe"),
                    ("TO", "Tocantins"),
                ],
                db_index=True,
                max_length=2,
            ),
        ),
        migrations.AddIndex(
            model_name="statespreadsheet",
            index=models.Index(fields=["date", "state"], name="covid19_sta_date_25063b_idx"),
        ),
    ]
