# Generated by Django 3.1.1 on 2020-12-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("covid19", "0015_auto_20201124_1216"),
    ]

    operations = [
        migrations.AlterField(model_name="statespreadsheet", name="date", field=models.DateField(),),
    ]
