# Generated by Django 3.1.1 on 2020-09-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="BlockedRequestsModels", new_name="BlockedRequest",),
    ]
