# Generated by Django 3.1.1 on 2020-09-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0003_auto_20200917_1920"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockedrequest", name="status_code", field=models.PositiveSmallIntegerField(default=429),
        ),
    ]
