# Generated by Django 3.1.1 on 2020-09-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0005_auto_20200917_1952"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockedrequest",
            name="path",
            field=models.TextField(blank=True, db_index=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="blockedrequest",
            name="source_ip",
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="blockedrequest",
            name="status_code",
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
