# Generated by Django 4.2.30 on 2026-05-18 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("traffic_control", "0007_auto_20200918_0253"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockedrequest",
            name="block_reason",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="blockedrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocked_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
