# Generated by Django 3.1.1 on 2020-10-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_control", "0007_auto_20200918_0253"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataUrlRedirect",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dataset_prev", models.SlugField(default="")),
                ("dataset_dest", models.SlugField(default="")),
                ("tablename_prev", models.SlugField(default="")),
                ("tablename_dest", models.SlugField(default="")),
                ("field_prev", models.SlugField(default="")),
                ("field_dest", models.SlugField(default="")),
            ],
        ),
    ]
