name: Django CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and start
      env:
        DB_SHM_SIZE: 1g
      run: |
        make build
        make start

    - name: Run tests
      run: make test

    - name: Run linter
      run: make lint-check

    - name: Cleanup
      if: always()
      run: make clean
